### ISSUE TITLE
Can't import Body and Occultation modules

### ISSUE THREAD

**Issue by Davide2due** [riogroup/SORA#90]
I have just installed the new SORA v0.3.1 and following the tutorial I ran into this issue importing Body and/or Occultation modules.

`In [9]: sys.version
Out[9]: '3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]'

In [10]: from sora import Body
Traceback (most recent call last):

  File F:\Programmazione\Anaconda\Lib\site-packages\sora\body\core.py:141 in __init__
    shape = self.shape

  File F:\Programmazione\Anaconda\Lib\site-packages\sora\body\meta.py:391 in shape
    raise AttributeError(f'{self.__class__.__name__} does not have attribute `shape`')

AttributeError: Body does not have attribute `shape`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  Cell In[10], line 1
    from sora import Body

  File F:\Programmazione\Anaconda\Lib\site-packages\sora\__init__.py:6
    from .occultation import Occultation

  File F:\Programmazione\Anaconda\Lib\site-packages\sora\occultation\__init__.py:2
    from .chord import *

  File F:\Programmazione\Anaconda\Lib\site-packages\sora\occultation\chord.py:7
    from .utils import add_arrow

  File F:\Programmazione\Anaconda\Lib\site-packages\sora\occultation\utils.py:233
    sun = Body(name='Sun', spkid='10', ephem=EphemHorizons(name='Sun', spkid=10, id_type='majorbody'),

  File F:\Programmazione\Anaconda\Lib\site-packages\sora\body\core.py:143 in __init__
    self.shape = self.radius.value

  File F:\Programmazione\Anaconda\Lib\site-packages\sora\body\meta.py:405 in shape
    self._shape = Ellipsoid(*value)

  File F:\Programmazione\Anaconda\Lib\site-packages\sora\body\shape\core.py:278 in __init__
    norm = v/np.sqrt(v.dot(v)).value

  File F:\Programmazione\Anaconda\Lib\site-packages\astropy\coordinates\representation.py:1488 in dot
    return erfa_ufunc.pdp(self.get_xyz(xyz_axis=-1),

  File F:\Programmazione\Anaconda\Lib\site-packages\astropy\coordinates\representation.py:1351 in get_xyz
    return np.stack([self._x, self._y, self._z], axis=xyz_axis)

  File <__array_function__ internals>:200 in stack

  File F:\Programmazione\Anaconda\Lib\site-packages\astropy\units\quantity.py:1683 in __array_function__
    return super().__array_function__(function, types, args, kwargs)

  File F:\Programmazione\Anaconda\Lib\site-packages\numpy\core\shape_base.py:471 in stack
    return _nx.concatenate(expanded_arrays, axis=axis, out=out,

  File <__array_function__ internals>:200 in concatenate

  File F:\Programmazione\Anaconda\Lib\site-packages\astropy\units\quantity.py:1688 in __array_function__
    args, kwargs, unit, out = function_helper(*args, **kwargs)

TypeError: concatenate() got an unexpected keyword argument 'dtype'`

Don't know if it is a problem of python or libraries versions.
I have:

- Astropy 6.1.0
- Astroquery 0.4.8
- Matplotlib 3.7.2
- NumPy 1.26.0
- SciPy 1.11.1
- SpiceyPy 6.0.0
- PyERFA 2.0.0
- Cartopy 0.23.0
- Shapely 2.0.4

**Comment by altairgomes** [comment]
Dear @Davide2due .

Thanks for reporting this issue. I tried to but could not reproduce the error with the same libraries.
In my case, I've run on Ubuntu 22.04. When possible I'll test on Windows.
By the error message, it seems a conflict between numpy and astropy.

> File F:\Programmazione\Anaconda\Lib\site-packages\astropy\units\quantity.py:1688 in array_function
> args, kwargs, unit, out = function_helper(*args, **kwargs)
> 
> TypeError: concatenate() got an unexpected keyword argument 'dtype'`

I recommend trying to update numpy and astropy.
I'll return to you when tested on Windows.

**Comment by Davide2due** [comment]
Thank you for the immediate response.
I did as you suggested. I upgraded numpy to 1.26.4 version and reinstalled astropy.

```
In [1]: from sora import Body
SORA version: 0.3.1

In [2]:
```

I gave the command above to verify if the error was corrected and it seems so.
Thank you for your support.
